name: build

on:
  push:
    branches:
      - main
    tags:
      - v*.**
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Determine Version
      run: |
        # determine version from tag
        export VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
        if [[ $VERSION != v* ]]
        then
          export VERSION=""
          echo "Building version-less (main or feature branch)"
        else
          # make version more Java-friendly by dropping the 'v'
          export VERSION=${VERSION:1:${#VERSION}}
          echo "Building as ${VERSION}"
        fi
        # store version in GitHub environment file
        echo "version=$VERSION" >> $GITHUB_ENV

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Linting
      run: ./gradlew spotlessCheck -x spotlessApply

    - name: Build ${{ env.version }}
      run: ./gradlew build koverXmlReport
      env:
        VERSION: ${{ env.version }}

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        files: ./build/reports/kover/report.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true

    - name: Publish to Maven Central
      if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'beta') && !contains(github.ref, 'alpha')
      run: |
        ./gradlew -Pversion=$VERSION publishToMavenCentral
      env:
        VERSION: ${{ env.version }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

  dependency-submission:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
